apiVersion: v2
name: laravel
description: A production-grade Helm chart for Laravel applications
type: application
version: nextjs-0.2.0
appVersion: "12.x"
keywords:
  - laravel
  - php
  - web
  - application
  - framework
maintainers:
  - name: 5ergiu
    url: https://github.com/5ergiu
home: https://github.com/5ergiu/helm-charts
sources:
  - https://github.com/5ergiu/helm-charts/tree/main/charts/laravel
  - https://github.com/laravel/laravel
icon: https://cdn.brandfetch.io/ide68-31CH/w/346/h/346/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1761211589926
annotations:
  category: Web Applications
  displayName: Laravel Helm Chart
  licenses: Apache-2.0
  artifacthub.io/changes: |-
    [

    { "kind": "changed", "description": "fixed workflows" },

    { "kind": "changed", "description": "ff" },

    { "kind": "changed", "description": "ff" },

    { "kind": "changed", "description": "ff" }

    ][

    { "kind": "changed", "description": "Initial tagged release" },

    { "kind": "changed", "description": "update chart documentation" },

    { "kind": "changed", "description": "update Chart.yaml metadata and annotiatinos" },

    { "kind": "changed", "description": "Update Charts annotations for artifactionhub.io/changes" }

    ]
