apiVersion: v2
name: laravel
description: A production-grade Helm chart for Laravel applications
type: application
version: 0.2.5
appVersion: "12.x"
keywords:
  - laravel
  - php
  - web
  - application
  - framework
maintainers:
  - name: 5ergiu
    url: https://github.com/5ergiu
home: https://github.com/5ergiu/helm-charts
sources:
  - https://github.com/5ergiu/helm-charts/tree/main/charts/laravel
  - https://github.com/laravel/laravel
icon: https://cdn.brandfetch.io/ide68-31CH/w/346/h/346/theme/dark/icon.jpeg?c=1bxid64Mup7aczewSAYMX&t=1761211589926
annotations:
  category: Web Applications
  displayName: Laravel Helm Chart
  licenses: Apache-2.0
  artifacthub.io/category: networking
  artifacthub.io/changes: |-
    - kind: changed
      description: multiple fixes
    - kind: changed
      description: multiple fixes applied to charts and docker images and workflows (#5)
      links:
        - name: GitHub PR
          url: https://github.com/5ergiu/helm-charts/pull/5
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: Laravel
      url: https://laravel.com/docs/12.x
    - name: Helm Chart
      url: https://github.com/5ergiu/helm-charts/tree/main/charts/laravel
    - name: Application
      url: https://github.com/laravel/laravel
    - name: Maintainer 5ergiu
      url: https://github.com/5ergiu
  artifacthub.io/prerelease: "true"
  artifacthub.io/signKey: |
    fingerprint: 7fa3b00701ad776b7d7f9cbb806c518b16320ae49ba814e6eee3c5ee4a6613c1
    url: https://github.com/5ergiu/helm-charts/blob/main/cosign.pub
