apiVersion: v2
name: laravel
description: A production-grade Helm chart for Laravel applications
type: application
version: 0.1.0
appVersion: "12.x"
keywords:
  - laravel
  - php
  - web
  - application
  - framework
maintainers:
  - name: 5ergiu
    url: https://github.com/5ergiu
home: https://github.com/5ergiu/helm-charts
sources:
  - https://github.com/5ergiu/helm-charts
  - https://github.com/laravel/laravel
icon: https://raw.githubusercontent.com/laravel/art/master/logo-lockup/5%20SVG/2%20CMYK/1%20Full%20Color/laravel-logolockup-cmyk-red.svg
annotations:
  category: Web Applications
  licenses: Apache-2.0
