apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "laravel.fullname" . }}-env
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.laravel.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
