{{- if .Values.horizon.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.fullname" . }}-horizon
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: horizon
spec:
  {{- if not .Values.horizon.autoscaling.enabled }}
  replicas: {{ .Values.horizon.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.horizon.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "laravel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: horizon
  template:
    metadata:
      annotations:
        checksum/config: {{ include "laravel.envConfigMap" . | sha256sum }}
        checksum/secret: {{ include "laravel.envSecret" . | sha256sum }}
        {{- with .Values.horizon.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "laravel.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: horizon
        {{- with .Values.horizon.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.horizon.podSecurityContext | nindent 8 }}
      containers:
        - name: horizon
          securityContext:
            {{- toYaml .Values.horizon.securityContext | nindent 12 }}
          image: {{ include "laravel.image" . }}
          imagePullPolicy: {{ include "laravel.imagePullPolicy" . }}
          command:
            {{- toYaml .Values.horizon.command | nindent 12 }}
          {{- with .Values.horizon.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            {{- include "laravel.envConfigMap" . | nindent 12 }}
            {{- include "laravel.envSecret" . | nindent 12 }}
          {{- with .Values.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.horizon.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.horizon.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.horizon.resources | nindent 12 }}
          {{- if or .Values.tmpfsVolumes.enabled .Values.persistence.enabled .Values.extraVolumeMounts }}
          volumeMounts:
            {{- include "laravel.volumeMounts" . | nindent 12 }}
          {{- end }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.tmpfsVolumes.enabled .Values.persistence.enabled .Values.extraVolumes }}
      volumes:
        {{- include "laravel.volumes" . | nindent 8 }}
      {{- end }}
      {{- with .Values.horizon.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.horizon.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.horizon.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
