{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
  annotations:
    {{- $top := . -}}
    {{- $ann := dict -}}
    {{- if $top.Values.ingress.annotations -}}
      {{- $ann = merge $ann $top.Values.ingress.annotations -}}
    {{- end -}}
    {{- if $top.Values.middleware.enabled -}}
      {{- $fullname := include "laravel.fullname" $top -}}
      {{- $middlewareStr := "" -}}
      {{- if $top.Values.middleware.redirectScheme.enabled }}
        {{- if ne $middlewareStr "" }}{{- $middlewareStr = printf "%s," $middlewareStr }}{{- end }}
        {{- $middlewareStr = printf "%s%s-%s-redirect-scheme" $middlewareStr $top.Release.Namespace $fullname -}}
      {{- end }}
      {{- if $top.Values.middleware.headers.enabled }}
        {{- if ne $middlewareStr "" }}{{- $middlewareStr = printf "%s," $middlewareStr }}{{- end }}
        {{- $middlewareStr = printf "%s%s-%s-headers" $middlewareStr $top.Release.Namespace $fullname -}}
      {{- end }}
      {{- if $top.Values.middleware.rateLimit.enabled }}
        {{- if ne $middlewareStr "" }}{{- $middlewareStr = printf "%s," $middlewareStr }}{{- end }}
        {{- $middlewareStr = printf "%s%s-%s-ratelimit" $middlewareStr $top.Release.Namespace $fullname -}}
      {{- end }}
      {{- if $top.Values.middleware.compress.enabled }}
        {{- if ne $middlewareStr "" }}{{- $middlewareStr = printf "%s," $middlewareStr }}{{- end }}
        {{- $middlewareStr = printf "%s%s-%s-compress" $middlewareStr $top.Release.Namespace $fullname -}}
      {{- end }}
      {{- if $top.Values.middleware.ipWhiteList.enabled }}
        {{- if ne $middlewareStr "" }}{{- $middlewareStr = printf "%s," $middlewareStr }}{{- end }}
        {{- $middlewareStr = printf "%s%s-%s-ipwhitelist" $middlewareStr $top.Release.Namespace $fullname -}}
      {{- end }}
      {{- if ne $middlewareStr "" }}
        {{- $_ := set $ann "traefik.ingress.kubernetes.io/router.middlewares" $middlewareStr -}}
      {{- end }}
    {{- end }}
    {{- toYaml $ann | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "laravel.fullname" $ }}-web
                port:
                  number: {{ $.Values.web.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
