{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "laravel.fullname" . }}-migration-{{ .Release.Revision }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: {{ .Values.migration.backoffLimit }}
  {{- if .Values.migration.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.migration.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "laravel.envConfigMap" . | sha256sum }}
        checksum/secret: {{ include "laravel.envSecret" . | sha256sum }}
        {{- with .Values.migration.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "laravel.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
        {{- with .Values.migration.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.migration.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: migration
          securityContext:
            {{- toYaml .Values.migration.securityContext | nindent 12 }}
          image: {{ include "laravel.migration.image" . }}
          imagePullPolicy: {{ include "laravel.migration.imagePullPolicy" . }}
          command:
            {{- toYaml .Values.migration.command | nindent 12 }}
          envFrom:
            {{- include "laravel.envConfigMap" . | nindent 12 }}
            {{- include "laravel.envSecret" . | nindent 12 }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
          volumeMounts:
            - name: bootstrap-cache
              mountPath: /var/www/html/bootstrap/cache
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: bootstrap-cache
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      {{- with .Values.migration.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migration.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migration.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
