apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel.fullname" . }}-secret
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.laravel.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
