apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel.fullname" . }}-secret
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
  {{- if .Values.migration.enabled }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.laravel.secrets }}
  {{- if $value }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
