apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nextjs.fullname" . }}-env
  labels:
    {{- include "nextjs.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.nextjs.publicEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.nextjs.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
