{{- if .Values.app.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextjs.fullname" . }}-app
  labels:
    {{- include "nextjs.app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.app.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  strategy:
    {{- toYaml .Values.app.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "nextjs.app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include "nextjs.envConfigMap" . | sha256sum }}
        checksum/secret: {{ include "nextjs.envSecret" . | sha256sum }}
        {{- with .Values.app.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "nextjs.app.selectorLabels" . | nindent 8 }}
        {{- with .Values.app.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nextjs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.app.podSecurityContext | nindent 8 }}
      {{- if or .Values.initContainers.verifyBuild.enabled .Values.extraInitContainers }}
      initContainers:
        {{- include "nextjs.initContainers" . | nindent 8 }}
      {{- end }}
      containers:
        - name: app
          securityContext:
            {{- toYaml .Values.app.securityContext | nindent 12 }}
          image: {{ include "nextjs.image" . }}
          imagePullPolicy: {{ include "nextjs.imagePullPolicy" . }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.targetPort }}
              protocol: TCP
          envFrom:
            {{- include "nextjs.envConfigMap" . | nindent 12 }}
            {{- include "nextjs.envSecret" . | nindent 12 }}
          {{- with .Values.extraEnvFrom }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.app.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.app.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.app.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.app.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.app.startupProbe.enabled }}
          startupProbe:
            {{- omit .Values.app.startupProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          {{- if or .Values.tmpfsVolumes.enabled .Values.persistence.enabled .Values.extraVolumeMounts }}
          volumeMounts:
            {{- include "nextjs.volumeMounts" . | nindent 12 }}
          {{- end }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if or .Values.tmpfsVolumes.enabled .Values.persistence.enabled .Values.extraVolumes }}
      volumes:
        {{- include "nextjs.volumes" . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
