apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextjs.fullname" . }}-secret
  labels:
    {{- include "nextjs.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.nextjs.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
