apiVersion: v2
name: nextjs
description: A production-grade Helm chart for Next.js applications
type: application
version: 0.2.3
appVersion: "16.x"
keywords:
  - nextjs
  - react
  - javascript
  - typescript
  - web
  - application
maintainers:
  - name: 5ergiu
    url: https://github.com/5ergiu
home: https://github.com/5ergiu/helm-charts
sources:
  - https://github.com/5ergiu/helm-charts/tree/main/charts/nextjs
  - https://github.com/vercel/next.js
icon: https://cdn.brandfetch.io/id2alue-rx/w/800/h/800/theme/dark/symbol.png?c=1bxid64Mup7aczewSAYMX&t=1762498501254
annotations:
  category: Web Applications
  displayName: Next.js Helm Chart
  licenses: Apache-2.0
  artifacthub.io/category: networking
  artifacthub.io/changes: |-
    - kind: changed
      description: fixing readmes
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: Next.js
      url: https://nextjs.org
    - name: Helm Chart
      url: https://github.com/5ergiu/helm-charts/tree/main/charts/nextjs
    - name: Application
      url: https://github.com/vercel/next.js
    - name: Maintainer 5ergiu
      url: https://github.com/5ergiu
  artifacthub.io/prerelease: "true"
  artifacthub.io/signKey: |
    fingerprint: 7fa3b00701ad776b7d7f9cbb806c518b16320ae49ba814e6eee3c5ee4a6613c1
    url: https://github.com/5ergiu/helm-charts/blob/main/cosign.pub
