apiVersion: v2
name: nextjs
description: A production-grade Helm chart for Next.js applications
type: application
version: 0.2.0
appVersion: "16.x"
keywords:
  - nextjs
  - react
  - javascript
  - typescript
  - web
  - application
maintainers:
  - name: 5ergiu
    url: https://github.com/5ergiu
home: https://github.com/5ergiu/helm-charts
sources:
  - https://github.com/5ergiu/helm-charts/tree/main/charts/nextjs
  - https://github.com/vercel/next.js
icon: https://cdn.brandfetch.io/id2alue-rx/w/800/h/800/theme/dark/symbol.png?c=1bxid64Mup7aczewSAYMX&t=1762498501254
annotations:
  category: Web Applications
  displayName: Next.js Helm Chart
  licenses: Apache-2.0
  artifacthub.io/changes: |-
    [

    { "kind": "changed", "description": "fixed workflows" },

    { "kind": "changed", "description": "ff" },

    { "kind": "changed", "description": "ff" },

    { "kind": "changed", "description": "ff" },

    { "kind": "changed", "description": "ff" }

    ][

    { "kind": "changed", "description": "Initial tagged release" },

    { "kind": "changed", "description": "update chart documentation" },

    { "kind": "changed", "description": "update Chart.yaml metadata and annotations" },

    { "kind": "changed", "description": "Update Charts annotations for artifactionhub.io/changes" }

    ]
