apiVersion: v2
name: nextjs
description: A production-grade Helm chart for Next.js applications
type: application
version: 0.1.0
appVersion: "16.x"
keywords:
  - nextjs
  - react
  - javascript
  - typescript
  - web
  - application
maintainers:
  - name: 5ergiu
    url: https://github.com/5ergiu
home: https://github.com/5ergiu/helm-charts
sources:
  - https://github.com/5ergiu/helm-charts
  - https://github.com/vercel/next.js
icon: https://cdn.brandfetch.io/id2alue-rx/w/800/h/800/theme/dark/symbol.png?c=1bxid64Mup7aczewSAYMX&t=1762498501254
annotations:
  category: Web Applications
  licenses: Apache-2.0
  artifacthub.io/changes: |2
        - kind: changed
          description: "feat(nextjs): add initial Next.js Helm chart with SSR/SSG support"
          links:
            - name: "Commit c1c2b7f"
              url: "https://github.com/5ergiu/helm-charts/commit/c1c2b7f"
